# https://sw.kovidgoyal.net/kitty/kittens/quick-access-terminal/#configuration

edge bottom
lines 15
hide_on_focus_loss yes
background_opacity .5

kitty_override font_size=20
kitty_override background_image=none
